### ISSUE TITLE
Аналіз, канцэпцыя і функцыянал

### ISSUE THREAD

**Issue by yahor** [plufmua/BusinessCalendar#1]
Перад пачаткам работ з кодам важна завершыць этап аналіза і дызайна сістэмы.

Ці ёсць?
- [x] Апісанне канцэпцыі і задач
- [x] Апісанне функцыянала і інтэрфейса, апісанне ралей карыстальнікаў
- [x] Тэхнічнае апісанне: патрабаванні да сервера(для 10 карыстальнікаў, 100 і больш), неабходныя праграммы і пакеты
- [x] Апісанне Структуры прыкладяння, классаў, АРІ, інтэрфейсаў і алгарытмаў
- [x] Дакументацыя карыстальніка

**Comment by plufmua** [comment]
Added into ReadMe.
